version: '3.8'

services:
  fastapi-server:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/winterboote
    networks:
      - teamEnet
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/winterboote
    networks:
      - teamEnet

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:latest
#    container_name: cadvisor
#    ports:
#      - "8080:8080"
#    volumes:
#      - /:/rootfs:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#    privileged: true
#    networks:
#      - teamEnet
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - teamEnet
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - teamEnet
#    depends_on:
#      - prometheus

#  k6:
#    image: grafana/k6
#    container_name: k6
#    volumes:
#      - ./test.js:/test.js
#    depends_on:
#      - fastapi-server
#    command: run /test.js
#    networks:
#      - teamEnet

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.5.0
    volumes:
      - ./monitoring/elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./app/logs:/app/logs:ro
    depends_on:
      - logstash
    networks:
      - teamEnet

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - teamEnet

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.5.0
    ports:
      - "5044:5044"
    volumes:
      - ./monitoring/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./monitoring/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - teamEnet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - teamEnet


volumes:
  mongo_data:
  elasticsearch_data:
networks:
  teamEnet:
    driver: bridge
