version: '3.8'

services:
  fastapi-server:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/winterboote
    networks:
      - teamEnet
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - teamEnet


networks:
  teamEnet:
    driver: bridge
