version: '3.8'

services:
  fastapi-server:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    networks:
      - teamEnet
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - teamEnet


networks:
  teamEnet:
    driver: bridge
