services:
  fastapi-server:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    volumes:
#      - ./app:/app
    restart: always

networks:
  teamEnet:
    driver: bridge